Update team data
eoscostarica/es.eoscostarica.io pull request #136
Opened 2022-08-10 22:15 UTC by hanakoori01

### ¿Qué hace este PR?

- Resuelve #135 

### Pasos 
1. Correr `yarn start`
2. Ir a Equipo

2022-08-11 14:18 UTC, xavier506 approved these changes
LGTM

2022-08-11 18:08 UTC, AngeloCG97 commented on src/pages/equipo.js
> +    color: "#ffffff",
Please review mobile version, color should be alternated between #f8f8f8 and #ffffff

2022-08-11 18:09 UTC, AngeloCG97 commented on src/pages/equipo.js
> +                      style={{ backgroundColor: isMobile ? person.color : "" }}
Please change style={{ backgroundColor: isMobile ? person.color : "" }} to bgColor Box prop

2022-08-11 18:10 UTC, AngeloCG97 commented on src/pages/equipo.js
> +                      style={{ backgroundColor: isMobile ? person.color : "" }}
Please change style={{ backgroundColor: isMobile ? person.color : "" }} to bgColor Box prop

2022-08-11 18:10 UTC, AngeloCG97 commented on src/pages/equipo.js
> +                      style={{ backgroundColor: isMobile ? person.color : "" }}
Please change style={{ backgroundColor: isMobile ? person.color : "" }} to bgColor Box prop

2022-08-11 18:10 UTC, AngeloCG97 commented on src/pages/equipo.js
> +                      style={{ backgroundColor: isMobile ? person.color : "" }}
Please change style={{ backgroundColor: isMobile ? person.color : "" }} to bgColor Box prop

2022-08-11 18:11 UTC, AngeloCG97 requested changes
Please review comments

2022-08-12 01:14 UTC, hanakoori01 commented
> Please review comments

On it!

2022-08-18 13:48 UTC, AngeloCG97 requested changes

2022-08-18 13:48 UTC, AngeloCG97 commented on src/pages/equipo.js
> +          <Box className="sectionHero" style={{ height: "auto" }}>
Please remove this inline style code

2022-08-18 13:48 UTC, AngeloCG97 commented on src/pages/equipo.js
> +          <Box className="sectionHeroMobile" style={{ paddingBottom: 0 }}>
Please remove this inline style code, use pb box prop

2022-08-18 13:48 UTC, AngeloCG97 commented on src/pages/equipo.js
> +                style={{ width: "200px", height: "250px" }}
remove inline style code

2022-08-18 13:48 UTC, AngeloCG97 commented on src/pages/equipo.js
> +                style={{ width: "200px", height: "250px" }}
remove inline style code

2022-08-18 13:48 UTC, AngeloCG97 commented on src/pages/equipo.js
> +                <TwitterIcon style={{ width: "30px", height: "30px" }} />
remove inline style code

2022-08-18 13:48 UTC, AngeloCG97 commented on src/pages/equipo.js
> +                <LinkedInIcon style={{ width: "30px", height: "30px" }} />
remove inline style code

2022-08-23 14:23 UTC, merged