Improve readme
eoscostarica/es.eoscostarica.io pull request #55
Opened 2021-03-29 16:02 UTC by AngeloCG97

### Improve readme

#54

### Steps to test
1.  Translate readme file
1. Fix image broke

2021-03-29 16:28 UTC, xavier506 requested changes

2021-03-29 16:28 UTC, xavier506 commented on README.md
>   <img style={{ width: "50%" }} src="https://raw.githubusercontent.com/eoscostarica/design-assets/master/logos/eosCR/fullColor-horizontal-transparent-white.png" />
These image styles dont seem to work on github

try something like this 

```
<p align="center">
	<a href="https://eoscostarica.io">
		<img src="https://github.com/eoscostarica/eos-rate/raw/master/docs/eoscostarica-logo-black.png" width="300">
	</a>
</p>

2021-03-30 02:57 UTC, xavier506 commented on README.md
cambiemos el h1 en la linea 1 por `# es.eoscostarica.io`

2021-03-30 02:58 UTC, xavier506 commented on README.md
> + ![EOS Costa Rica](https://raw.githubusercontent.com/eoscostarica/es.eoscostarica.io/master/static/img/screenshot_home.png)
usamos un screenshot del sitio en español?

2021-03-30 19:46 UTC, xavier506 requested changes
remove extra div

2021-04-07 23:34 UTC, xavier506 commented on README.md
> +EOS Costa Rica es un productor independiente, autofinanciado, de bloques Génesis que proporciona una infraestructura estable y segura para las cadenas de bloques EOSIO. Apoyamos el software de código
es un productor ... productor de bloques (Block Producer)

2021-04-12 15:51 UTC, JeanVegaD approved these changes

2021-04-12 19:07 UTC, merged